SELECT DISTINCT emp.masterResponseid, emp.AnonymousID, emp.HotelInncode, emp.HotelBrand, emp.Generation, emp.Department, emp.FullTimePartTime, emp.Tenure, emp.ManagementLevel, emp.Engagement1, emp.Engagement2, emp.RecommendToWork, emp.RecommendToStay, emp.HiltonCSR, emp.WellInformed, emp.JobSatisfaction, emp.WorkEnvironment1, emp.TreatmentRespect1, emp.Engagement3, emp.AppreciatedAtWork, emp.WorkEnvironment2, emp.TreatmentRespect2, emp.MyJob2, emp.AdequateResources1, emp.AdequateResources2, emp.LearningDevelopment1, emp.Engagement4, emp.SatisfactionWithPay, emp.RewardsBenefits2, emp.RewardsBenefits3, emp.RewardsJustice, emp.LearningDevelopment2, emp.LearningDevelopment3, emp.TreatmentRespect3, emp.WorkEnvironment3, emp.WorkLifeBalance1, emp.WorkLifeBalance2, emp.JobExpectations1, emp.JobExpectations2, emp.LearningDevelopment4, emp.LearningDevelopment5, 
emp.Management1, emp.Management2, emp.TreatmentRespect4, emp.Management3, emp.Management4, emp.WorkEnvironment4, emp.LearningDevelopment6, emp.Management5, emp.ManagementDEI, emp.LearningDevelopment7, emp.WellBeing1, emp.WellBeing2, emp.WorkEnvironment5, emp.WorkEnvironment6, emp.Management6, emp.Management7, emp.Management8, emp.IntentToStay, emp.IntentToStayHighLow, emp.EmployeeWellBeing, emp.EngagedAtWork, emp.AdequateWorkResources, emp.ClearJobExpectations, emp.RewardsBenefits, emp.LearningDevelopment, emp.WorkEnvironment, emp.WorkLifeBalance, 
avg(mgr.Generation) as MgrGeneration, (avg(mgr.Generation)-avg(emp.Generation)) as GenerationGap,
avg(mgr.Tenure) as MgrTenure, (avg(mgr.Tenure)-avg(emp.Tenure)) as TenureGap,
avg(mgr.Engagement1) as MgrEngagement1, (avg(mgr.Engagement1)-avg(emp.Engagement1)) as Engagement1Gap,
avg(mgr.Engagement2) as MgrEngagement2, (avg(mgr.Engagement2)-avg(emp.Engagement2)) as Engagement2Gap,
avg(mgr.RecommendToWork) as MgrRecommendToWork, (avg(mgr.RecommendToWork)-avg(emp.RecommendToWork)) as RecommendToWorkGap,
avg(mgr.RecommendToStay) as MgrRecommendToStay, (avg(mgr.RecommendToStay)-avg(emp.RecommendToStay)) as RecommendToStayGap,
avg(mgr.HiltonCSR) as MgrHiltonCSR, (avg(mgr.HiltonCSR)-avg(emp.HiltonCSR)) as HiltonCSRGap,
avg(mgr.WellInformed) as MgrWellInformed, (avg(mgr.WellInformed)-avg(emp.WellInformed)) as WellInformedGap,
avg(mgr.JobSatisfaction) as MgrJobSatisfaction, (avg(mgr.JobSatisfaction)-avg(emp.JobSatisfaction)) as JobSatisfactionGap,
avg(mgr.WorkEnvironment1) as MgrWorkEnvironment1, (avg(mgr.WorkEnvironment1)-avg(emp.WorkEnvironment1)) as WorkEnvironment1Gap,
avg(mgr.TreatmentRespect1) as MgrTreatmentRespect1, (avg(mgr.TreatmentRespect1)-avg(emp.TreatmentRespect1)) as TreatmentRespect1Gap,
avg(mgr.Engagement3) as MgrEngagement3, (avg(mgr.Engagement3)-avg(emp.Engagement3)) as Engagement3Gap,
avg(mgr.AppreciatedAtWork) as MgrAppreciatedAtWork, (avg(mgr.AppreciatedAtWork)-avg(emp.AppreciatedAtWork)) as AppreciatedAtWorkGap,
avg(mgr.WorkEnvironment2) as MgrWorkEnvironment2, (avg(mgr.WorkEnvironment2)-avg(emp.WorkEnvironment2)) as WorkEnvironment2Gap,
avg(mgr.TreatmentRespect2) as MgrTreatmentRespect2, (avg(mgr.TreatmentRespect2)-avg(emp.TreatmentRespect2)) as TreatmentRespect2Gap,
avg(mgr.MyJob2) as MgrMyJob2, (avg(mgr.MyJob2)-avg(emp.MyJob2)) as MyJob2Gap,
avg(mgr.AdequateResources1) as MgrAdequateResources1, (avg(mgr.AdequateResources1)-avg(emp.AdequateResources1)) as AdequateResources1Gap,
avg(mgr.AdequateResources2) as MgrAdequateResources2, (avg(mgr.AdequateResources2)-avg(emp.AdequateResources2)) as AdequateResources2Gap,
avg(mgr.LearningDevelopment1) as MgrLearningDevelopment1, (avg(mgr.LearningDevelopment1)-avg(emp.LearningDevelopment1)) as LearningDevelopment1Gap,
avg(mgr.Engagement4) as MgrEngagement4, (avg(mgr.Engagement4)-avg(emp.Engagement4)) as Engagement4Gap,
avg(mgr.SatisfactionWithPay) as MgrSatisfactionWithPay, (avg(mgr.SatisfactionWithPay)-avg(emp.SatisfactionWithPay)) as SatisfactionWithPayGap,
avg(mgr.RewardsBenefits2) as MgrRewardsBenefits2, (avg(mgr.RewardsBenefits2)-avg(emp.RewardsBenefits2)) as RewardsBenefits2Gap,
avg(mgr.RewardsBenefits3) as MgrRewardsBenefits3, (avg(mgr.RewardsBenefits3)-avg(emp.RewardsBenefits3)) as RewardsBenefits3Gap,
avg(mgr.RewardsJustice) as MgrRewardsJustice, (avg(mgr.RewardsJustice)-avg(emp.RewardsJustice)) as RewardsJusticeGap,
avg(mgr.LearningDevelopment2) as MgrLearningDevelopment2, (avg(mgr.LearningDevelopment2)-avg(emp.LearningDevelopment2)) as LearningDevelopment2Gap,
avg(mgr.LearningDevelopment3) as MgrLearningDevelopment3, (avg(mgr.LearningDevelopment3)-avg(emp.LearningDevelopment3)) as LearningDevelopment3Gap,
avg(mgr.TreatmentRespect3) as MgrTreatmentRespect3, (avg(mgr.TreatmentRespect3)-avg(emp.TreatmentRespect3)) as TreatmentRespect3Gap,
avg(mgr.WorkEnvironment3) as MgrWorkEnvironment3, (avg(mgr.WorkEnvironment3)-avg(emp.WorkEnvironment3)) as WorkEnvironment3Gap,
avg(mgr.WorkLifeBalance1) as MgrWorkLifeBalance1, (avg(mgr.WorkLifeBalance1)-avg(emp.WorkLifeBalance1)) as WorkLifeBalance1Gap,
avg(mgr.WorkLifeBalance2) as MgrWorkLifeBalance2, (avg(mgr.WorkLifeBalance2)-avg(emp.WorkLifeBalance2)) as WorkLifeBalance2Gap,
avg(mgr.JobExpectations1) as MgrJobExpectations1, (avg(mgr.JobExpectations1)-avg(emp.JobExpectations1)) as JobExpectations1Gap,
avg(mgr.JobExpectations2) as MgrJobExpectations2, (avg(mgr.JobExpectations2)-avg(emp.JobExpectations2)) as JobExpectations2Gap,
avg(mgr.LearningDevelopment4) as MgrLearningDevelopment4, (avg(mgr.LearningDevelopment4)-avg(emp.LearningDevelopment4)) as LearningDevelopment4Gap,
avg(mgr.LearningDevelopment5) as MgrLearningDevelopment5, (avg(mgr.LearningDevelopment5)-avg(emp.LearningDevelopment5)) as LearningDevelopment5Gap,
avg(mgr.Management1) as MgrManagement1, (avg(mgr.Management1)-avg(emp.Management1)) as Management1Gap,
avg(mgr.Management2) as MgrManagement2, (avg(mgr.Management2)-avg(emp.Management2)) as Management2Gap,
avg(mgr.TreatmentRespect4) as MgrTreatmentRespect4, (avg(mgr.TreatmentRespect4)-avg(emp.TreatmentRespect4)) as TreatmentRespect4Gap,
avg(mgr.Management3) as MgrManagement3, (avg(mgr.Management3)-avg(emp.Management3)) as Management3Gap,
avg(mgr.Management4) as MgrManagement4, (avg(mgr.Management4)-avg(emp.Management4)) as Management4Gap,
avg(mgr.WorkEnvironment4) as MgrWorkEnvironment4, (avg(mgr.WorkEnvironment4)-avg(emp.WorkEnvironment4)) as WorkEnvironment4Gap,
avg(mgr.LearningDevelopment6) as MgrLearningDevelopment6, (avg(mgr.LearningDevelopment6)-avg(emp.LearningDevelopment6)) as LearningDevelopment6Gap,
avg(mgr.Management5) as MgrManagement5, (avg(mgr.Management5)-avg(emp.Management5)) as Management5Gap,
avg(mgr.ManagementDEI) as MgrManagementDEI, (avg(mgr.ManagementDEI)-avg(emp.ManagementDEI)) as ManagementDEIGap,
avg(mgr.LearningDevelopment7) as MgrLearningDevelopment7, (avg(mgr.LearningDevelopment7)-avg(emp.LearningDevelopment7)) as LearningDevelopment7Gap,
avg(mgr.WellBeing1) as MgrWellBeing1, (avg(mgr.WellBeing1)-avg(emp.WellBeing1)) as WellBeing1Gap,
avg(mgr.WellBeing2) as MgrWellBeing2, (avg(mgr.WellBeing2)-avg(emp.WellBeing2)) as WellBeing2Gap,
avg(mgr.WorkEnvironment5) as MgrWorkEnvironment5, (avg(mgr.WorkEnvironment5)-avg(emp.WorkEnvironment5)) as WorkEnvironment5Gap,
avg(mgr.WorkEnvironment6) as MgrWorkEnvironment6, (avg(mgr.WorkEnvironment6)-avg(emp.WorkEnvironment6)) as WorkEnvironment6Gap,
avg(mgr.Management6) as MgrManagement6, (avg(mgr.Management6)-avg(emp.Management6)) as Management6Gap,
avg(mgr.Management7) as MgrManagement7, (avg(mgr.Management7)-avg(emp.Management7)) as Management7Gap,
avg(mgr.Management8) as MgrManagement8, (avg(mgr.Management8)-avg(emp.Management8)) as Management8Gap,
avg(mgr.IntentToStay) as MgrIntentToStay, (avg(mgr.IntentToStay)-avg(emp.IntentToStay)) as IntentToStayGap,
avg(mgr.IntentToStayHighLow) as MgrIntentToStayHighLow, (avg(mgr.IntentToStayHighLow)-avg(emp.IntentToStayHighLow)) as IntentToStayHighLowGap,
avg(mgr.EmployeeWellBeing) as MgrEmployeeWellBeing, (avg(mgr.EmployeeWellBeing)-avg(emp.EmployeeWellBeing)) as EmployeeWellBeingGap,
avg(mgr.EngagedAtWork) as MgrEngagedAtWork, (avg(mgr.EngagedAtWork)-avg(emp.EngagedAtWork)) as EngagedAtWorkGap,
avg(mgr.AdequateWorkResources) as MgrAdequateWorkResources, (avg(mgr.AdequateWorkResources)-avg(emp.AdequateWorkResources)) as AdequateWorkResourcesGap,
avg(mgr.ClearJobExpectations) as MgrClearJobExpectations, (avg(mgr.ClearJobExpectations)-avg(emp.ClearJobExpectations)) as ClearJobExpectationsGap,
avg(mgr.RewardsBenefits) as MgrRewardsBenefits, (avg(mgr.RewardsBenefits)-avg(emp.RewardsBenefits)) as RewardsBenefitsGap,
avg(mgr.LearningDevelopment) as MgrLearningDevelopment, (avg(mgr.LearningDevelopment)-avg(emp.LearningDevelopment)) as LearningDevelopmentGap,
avg(mgr.WorkEnvironment) as MgrWorkEnvironment, (avg(mgr.WorkEnvironment)-avg(emp.WorkEnvironment)) as WorkEnvironmentGap,
avg(mgr.WorkLifeBalance) as MgrWorkLifeBalance, (avg(mgr.WorkLifeBalance)-avg(emp.WorkLifeBalance)) as WorkLifeBalanceGap
FROM employee as emp, employee as mgr
WHERE mgr.HotelInncode = emp.HotelInncode
    AND mgr.Department = emp.Department
	AND mgr.ManagementLevel = 2
	AND emp.ManagementLevel = 3
	AND mgr.masterResponseid IS NOT null
GROUP BY emp.masterResponseid, emp.AnonymousID, emp.HotelInncode, emp.HotelBrand, emp.Generation, emp.Department, emp.FullTimePartTime, emp.Tenure, emp.ManagementLevel, emp.Engagement1, emp.Engagement2, emp.RecommendToWork, emp.RecommendToStay, emp.HiltonCSR, emp.WellInformed, emp.JobSatisfaction, emp.WorkEnvironment1, emp.TreatmentRespect1, emp.Engagement3, emp.AppreciatedAtWork, emp.WorkEnvironment2, emp.TreatmentRespect2, emp.MyJob2, emp.AdequateResources1, emp.AdequateResources2, emp.LearningDevelopment1, emp.Engagement4, emp.SatisfactionWithPay, emp.RewardsBenefits2, emp.RewardsBenefits3, emp.RewardsJustice, emp.LearningDevelopment2, emp.LearningDevelopment3, emp.TreatmentRespect3, emp.WorkEnvironment3, emp.WorkLifeBalance1, emp.WorkLifeBalance2, emp.JobExpectations1, emp.JobExpectations2, emp.LearningDevelopment4, emp.LearningDevelopment5, 
emp.Management1, emp.Management2, emp.TreatmentRespect4, emp.Management3, emp.Management4, emp.WorkEnvironment4, emp.LearningDevelopment6, emp.Management5, emp.ManagementDEI, emp.LearningDevelopment7, emp.WellBeing1, emp.WellBeing2, emp.WorkEnvironment5, emp.WorkEnvironment6, emp.Management6, emp.Management7, emp.Management8, emp.IntentToStay, emp.IntentToStayHighLow, emp.EmployeeWellBeing, emp.EngagedAtWork, emp.AdequateWorkResources, emp.ClearJobExpectations, 
emp.RewardsBenefits, emp.LearningDevelopment, emp.WorkEnvironment, emp.WorkLifeBalance
LIMIT 10000
	